-- 01 - SET THE ROLE, VIRTUAL WARE HOUSE AND DATABASE
USE ROLE accountadmin;
USE WAREHOUSE compute_wh;
USE PLURALSIGHT_DATM;

-- 02 - RUN THE CLONE COMMAND

CREATE OR REPLACE SCHEMA STAGING CLONE RAW;

-- 03 - DATA QUALITY customer_survey_data
-- TABLE: customer_survey_data
-- SOME OF THE DATA IN THE NAME COLUMN HAVE "-" CHARACTERS BETWEEN THE FIRST AND LAST.
-- SOME OF THE GENDER COLUMNS HAVE "M" OR "F" INSTEAD OF "MALE" OR "FEMALE".
-- ADD A STATE TABLE SO THAT YOU CAN VISUALIZE CUSTOMERS LOCATIONS BETTER, RIGHT NOW ONLY THE CITY COLUMN EXISTS.

SELECT * FROM PLURALSIGHT_DATM.STAGING.CUSTOMER_SURVEY_DATA;

-- 04 - DATA QUALITY customer_transactions
-- TABLE: customer_transactions
-- COMBINE THE DATE AND TIME COLUMNS TO A SINGLE TRANSACTION DATETIME COLUMN.
-- ADD A TOTAL_TRANSACTION_COUNT COLUMN AND A TOTAL_SPEND COLUMN TO BETTER UNDERSTAND CUSTOMER BEHAVIOR.

SELECT * FROM PLURALSIGHT_DATM.STAGING.CUSTOMER_TRANSACTIONS;

-- 05 - DATA QUALITY employee_engagement_survey
-- TABLE: employee_engagement_survey
-- DUPLICATE RECORDS, IDENTIFY AND REMOVE AND DE-DUPLICATE SURVEY RESULTS DATA.
-- MISSING DATA, SOME EMPLOYEES DID NOT SUBMIT AN ENGAGEMENT SURVEY, IDENTIFY THE EMPLOYEE WHOS DID NOT PARTICIPATE.
-- ADD A "AGE-BIN" COLUMN, THAT GROUPS EMPLOYEES OF DIFFERENT AGE GROUPS TOGETHER. I.E. "20-29","30-39","40-69".

SELECT * FROM PLURALSIGHT_DATM.STAGING.EMPLOYEE_ENGAGEMENT_SURVEY;